export const GRADE_NAME_LIST = 'grade_name_list'
export const USERINFO = 'userinfo'
export const USER_GRADE_LIST = 'user_grade_list'
export const TIPS_LIST = 'tips_list'
export const PAPER_PACKAGE = 'paper_package'
export const ADD_GRADEID_TO_PAPERPACKAGE = 'add_gradeId_to_paperPackage'
export const BACKGROUND_IMG = 'background_img'